const PubList = {
  first: [
    {
      authors: [
        'Knight JDR',
        'Samavarchi-Tehrani P',
        'Tyers M',
        'Gingras AC',
      ],
      date: 'Submitted',
      journal: 'BioRxiv 532523 [Preprint]',
      key: 'tbdKnightInprep',
      pages: 'https://doi.org/10.1101/532523',
      title: 'Gene Information eXtension (GIX): effortless retrieval of gene product information on any website',
    },
    {
      authors: [
        'Knight JDR',
        'Choi H',
        'Gupta G',
        'Pelletier L',
        'Raught B',
        'Nesvizhskii AI',
        'Gingras AC',
      ],
      date: '2017',
      key: 'natmethods2017',
      journal: 'Nature Methods',
      pages: '14:645-646',
      title: 'ProHits-viz: a suite of web-tools for visualizing interaction proteomics data',
    },
    {
      authors: [
        'Knight JDR',
        'Liu G',
        'Zhang JP',
        'Pasculescu A',
        'Choi H',
        'Gingras AC',
      ],
      date: '2015',
      journal: 'Proteomics',
      key: 'proteomics2015',
      pages: '15:1432-1436',
      title: 'A web-tool for visualizing quantitative protein-protein interaction data',
    },
    {
      authors: [
        'Knight JDR',
        'Pawson T',
        'Gingras AC',
      ],
      date: '2013',
      journal: 'Journal of Proteomics',
      key: 'jop2013',
      pages: '81:43-55',
      title: 'Profiling the kinome: current capabilities and future challenges',
    },
    {
      authors: [
        'Knight JDR',
        'Kothary R',
      ],
      date: '2012',
      journal: 'Kinome',
      key: 'kinome2012',
      pages: '1:1-3',
      title: 'The extracellular kinome',
    },
    {
      authors: [
        'Knight JDR',
        'Tian R',
        'Lee REC',
        'Wang F',
        'Beauvais A',
        'Zou H',
        'Megeney LA',
        'Gingras AC',
        'Pawson T',
        'Figeys D',
        'Kothary R',
      ],
      date: '2012',
      journal: 'Skeletal Muscle',
      key: 'skelmusc2012',
      pages: '2:5',
      title: `A novel whole-cell lysate kinase assay identifies substrates of
        the p38 MAPK in differentiating myoblasts`,
    },
    {
      authors: [
        'Knight JDR',
        'Kothary R',
      ],
      date: '2011',
      journal: 'Skeletal Muscle',
      key: 'skelmusc2011',
      pages: '1:29',
      title: 'The myogenic kinome: protein kinases critical to mammalian skeletal myogenesis',
    },
    {
      authors: [
        'Knight JDR',
        'Hamelberg D',
        'McCammon JA',
        'Kothary R',
      ],
      date: '2009',
      journal: 'Proteins: Structure, Function, and Bioinformatics',
      key: 'proteins2009',
      pages: '76:527-535',
      title: 'The role of conserved water molecules in the catalytic domain of protein kinases',
    },
    {
      authors: [
        'Knight JDR',
        'Qian B',
        'Baker D',
        'Kothary R',
      ],
      date: '2007',
      journal: 'PLoS ONE',
      key: 'plos2007',
      pages: '2:e982',
      title: 'Conservation, variability and the modeling of active protein kinases',
    },
  ],
  co: [
    {
      authors: [
        'Lambert JP',
        'Picaud S',
        'Fujisawa T',
        'Hou H',
        'Savitsky P',
        'Uusküla-Reimand L',
        'Gupta G',
        'Abdouni H',
        'Lin ZY',
        'Tucholska M',
        'Knight JDR',
        'Gonzalez-Badillo B',
        'St-Denis N',
        'Newman J',
        'Stucki M',
        'Pelletier L',
        'Bandeira N',
        'Wilson M',
        'Filippakopoulos P',
        'Gingras AC',
      ],
      date: '2019',
      journal: 'Molecular Cell',
      key: 'molcellLambert2019',
      pages: '73:621-638',
      title: 'Interactome Rewiring Following Pharmacological Targeting of BET Bromodomains',
    },
    {
      authors: [
        'Youn JY',
        'Dunham WH',
        'Hong SJ',
        'Knight JDR',
        'Chen GI',
        'Bagci H',
        'Bashkurov M',
        'Rathod B',
        'MacLeod G',
        'Eng SWM',
        'Angers S',
        'Morris Q',
        'Fabian M',
        'Côté JF',
        'Gingras AC',
      ],
      date: '2018',
      journal: 'Molecular Cell',
      key: 'molcellYoun2018',
      pages: '69:517-532',
      title: `High-density proximity mapping reveals the subcellular
        organization of mRNA-associated granules and bodies`,
    },
    {
      authors: [
        'Couzens AL',
        'Xiong S',
        'Knight JDR',
        'Mao DY',
        'Guettler S',
        'Picaud S',
        'Kurinov I',
        'Filippakopoulos P',
        'Sicheri F',
        'Gingras AC',
      ],
      date: '2017',
      journal: 'Molecular and Cellular Proteomics',
      key: 'mcpCouzens2017',
      pages: '16:1098-1110',
      title: 'MOB1 mediated phospho-recognition in the core mammalian Hippo pathway',
    },
    {
      authors: [
        'St-Denis N',
        'Gupta GD',
        'Lin ZY',
        'Gonzalez-Badillo B',
        'Veri AO',
        'Knight JDR',
        'Rajendran D',
        'Couzens AL',
        'Currie KW',
        'Tkach JM',
        'Cheung SWT',
        'Pelletier L',
        'Gingras AC',
      ],
      date: '2016',
      journal: 'Cell Reports',
      key: 'cellrepStdenis2016',
      pages: '17: 2488-2501',
      title: `Phenotypic and interaction profiling of the human phosphatases
        identifies diverse mitotic regulators`,
    },
    {
      authors: [
        'Liu G',
        'Knight JDR',
        'Zhang JP',
        'Tsou CC',
        'Wang J',
        'Lambert JP',
        'Larsen B',
        'Tyers M',
        'Raught B',
        'Bandeira N',
        'Nesvizhskii A',
        'Choi H',
        'Gingras AC',
      ],
      date: '2016',
      journal: 'J Proteomics',
      key: 'jprotLiu2016',
      pages: '149: 64-68',
      title: 'Data Independent Acquisition analysis in ProHits 4.0',
    },
    {
      authors: [
        'Teo G',
        'Koh H',
        'Fermin D',
        'Lambert JP',
        'Knight JDR',
        'Gingras AC',
        'Choi HW',
      ],
      date: '2016',
      journal: 'Proteomics',
      key: 'proteomicsTeo2016',
      pages: '16: 15-16',
      title: `SAINTq: Scoring protein-protein interactions in affinity purification –
        mass spectrometry experiments with fragment or peptide intensity data`,
    },
    {
      authors: [
        'De Kreuk BJ',
        'Gingras AR',
        'Knight JDR',
        'Liu JJ',
        'Gingras AC',
        'Ginsberg MH',
      ],
      date: '2016',
      journal: 'eLife',
      key: 'elifeKreuk2016',
      pages: '5: e11394',
      title: `Heart of Glass Anchors Rasip1 at Endothelial Cell-Cell Junctions to
        Support Vascular Integrity`,
    },
    {
      authors: [
        'Gupta GD',
        'Coyaud É',
        'Gonçalves J',
        'Mojarad BA',
        'Liu Y',
        'Wu Q',
        'Gheiratmand L',
        'Comartin D',
        'Tkach JM',
        'Cheung SW',
        'Bashkurov M',
        'Hasegan M',
        'Knight JDR',
        'Lin ZY',
        'Schueler M',
        'Hildebrandt F',
        'Moffat J',
        'Gingras AC',
        'Raught B',
        'Pelletier L',
      ],
      date: '2015',
      journal: 'Cell',
      key: 'cellGupta2015',
      pages: '163: 1484-99',
      title: 'A dynamic protein interaction landscape of the human centrosome-cilium interface',
    },
    {
      authors: [
        'Wang J',
        'Tucholska M',
        'Knight JDR',
        'Lambert JP',
        'Larsen B',
        'Tate S',
        'Gingras AC',
        'Bandeira N',
      ],
      date: '2015',
      journal: 'Nature Methods',
      key: 'natmethWang2015',
      pages: '12: 1106-8',
      title: 'MSPLIT-DIA: Sensitive peptide identification for data-independent acquisition',
    },
    {
      authors: [
        'Lambert JP',
        'Tucholska M',
        'Go C',
        'Knight JDR',
        'Gingras AC',
      ],
      date: '2015',
      journal: 'Journal of Proteomics',
      key: 'jprotLambert2015',
      pages: '118:81-94',
      title: `Proximity biotinylation and affinity purification are complimentary
        approaches for the interactome mapping of chromatin-associated protein complexes`,
    },
    {
      authors: [
        'Lant B',
        'Yu B',
        'Goudreault M',
        'Holmyard D',
        'Knight JDR',
        'Xu P',
        'Zhao X',
        'Chin K',
        'Wallace E',
        'Zhen M',
        'Gingras AC',
        'Derry WB',
      ],
      date: '2015',
      journal: 'Nature Communications',
      key: 'natcommLant2015',
      pages: '6:6449',
      title: 'CCM-3/STRIPAK promotes seamless tube extension through endosome recycling',
    },
    {
      authors: [
        'Turowec JP',
        'Zukowsli SA',
        'Knight JDR',
        'Smalley DM',
        'Graves LM',
        'Johnson GL',
        'Li SS',
        'Lajoie GA',
        'Litchfield DW',
      ],
      date: '2014',
      journal: 'Molecular and Cellular Proteomics',
      key: 'mcpTurowec2014',
      pages: '13:1184-97',
      title: `An unbiased, proteomic screen reveals caspase cleavage is positively
        and negatively regulated by substrate phosphorylation`,
    },
    {
      authors: [
        'Couzens AL',
        'Knight JDR',
        'Kean MJ',
        'Teo G',
        'Weiss A',
        'Dunham W',
        'Lin Z-Y',
        'Bagshaw RD',
        'Sicheri F',
        'Pawson T',
        'Wrana J',
        'Choi H',
        'Gingras AC',
      ],
      date: '2013',
      journal: 'Science Signaling',
      key: 'scisigCouzens2013',
      pages: '6: rs15',
      title: `Protein interaction network of the mammalian Hippo pathway reveals
        mechanisms of kinase-phosphatase interactions`,
    },
    {
      authors: [
        'Costa B',
        'Kean MJ',
        'Ast V',
        'Knight JDR',
        'Mett A',
        'Levy Z',
        'Ceccarelli DF',
        'Badillo BG',
        'Eils R',
        'König R',
        'Gingras AC',
        'Fainzilber M',
      ],
      date: '2012',
      journal: 'Journal of Biological Chemistry',
      key: 'jbcCosta2012',
      pages: '287: 29285–29289',
      title: `STK25 mediates TrkA and CCM2 dependent death in pediatric tumor
        cells of neural origin`,
    },
    {
      authors: [
        'Fukuda K',
        'Knight JDR',
        'Piszczek G',
        'Kothary R',
        'Qin J',
      ],
      date: '2011',
      journal: 'Journal of Biological Chemistry',
      key: 'jbcFukuda2011',
      pages: '286:21886–21895',
      title: `Biochemical, proteomic, structural, and thermodynamic characterizations
        of ILK: Cross-validation of the pseudokinase`,
    },
  ],
};
export default PubList;
